import React, { useState } from 'react';

// Пример данных о швах
const seamData = [
  {
    name: 'Алжирский переплетенный шов',
    description: 'Шов с переплетением, характерный для алжирской вышивки.',
    advantages: 'Оригинальный внешний вид, прочность.',
    disadvantages: 'Сложность выполнения.',
    fabric: 'Хлопок, лен',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Переплетение края',
    embroidery: true,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Английский',
    description: 'Шов, часто используемый в традиционном английском рукоделии.',
    advantages: 'Эстетичный, аккуратный.',
    disadvantages: 'Не подходит для толстых тканей.',
    fabric: 'Тонкие ткани',
    application: 'Декоративные элементы, вышивка.',
    edgeTechnique: 'Обработка края',
    embroidery: true,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'В замок припуск на вырез горловины',
    description: 'Шов для обработки выреза горловины.',
    advantages: 'Эстетичный вид, предотвращает осыпание.',
    disadvantages: 'Может быть сложным для новичков.',
    fabric: 'Все типы тканей',
    application: 'Шитье одежды.',
    edgeTechnique: 'Припуск на вырез',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'В раскол',
    description: 'Шов, используемый для создания декоративных разрезов.',
    advantages: 'Подходит для декоративных элементов.',
    disadvantages: 'Необходима точность при выполнении.',
    fabric: 'Все типы тканей',
    application: 'Декоративные элементы.',
    edgeTechnique: 'Разрез',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'В рельеф',
    description: 'Шов, который образует рельефные узоры на ткани.',
    advantages: 'Создает интересный текстурный эффект.',
    disadvantages: 'Требует определенного навыка.',
    fabric: 'Все типы тканей',
    application: 'Декорирование одежды.',
    edgeTechnique: 'Рельефный узор',
    embroidery: true,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'В россыпь',
    description: 'Шов для создания декоративных элементов в виде россыпи.',
    advantages: 'Эффектный внешний вид.',
    disadvantages: 'Может потребовать много времени.',
    fabric: 'Легкие ткани',
    application: 'Декорирование одежды.',
    edgeTechnique: 'Россыпь',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'В рулоне',
    description: 'Шов, использующийся для обработки краев ткани.',
    advantages: 'Прочный и аккуратный.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Все типы тканей',
    application: 'Обработка краев.',
    edgeTechnique: 'Рулон',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  // Добавьте остальные швы здесь
  {
    name: 'Вдоль края',
    description: 'Шов, обработка края ткани.',
    advantages: 'Простой в выполнении, аккуратный.',
    disadvantages: 'Не всегда подходит для толстых тканей.',
    fabric: 'Тонкие и средние ткани',
    application: 'Обработка края одежды.',
    edgeTechnique: 'Обработка края',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 2,
  },
  {
    name: 'Вилка',
    description: 'Шов, который имеет вид вилки.',
    advantages: 'Эстетичный вид, уникальный.',
    disadvantages: 'Сложность выполнения.',
    fabric: 'Все типы тканей',
    application: 'Декоративные элементы.',
    edgeTechnique: 'Форма вилки',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Владимирский верхошов',
    description: 'Шов, используемый в традиционном русском рукоделии.',
    advantages: 'Традиционный вид, прочность.',
    disadvantages: 'Может требовать навыка.',
    fabric: 'Лен, хлопок',
    application: 'Традиционные вышивки.',
    edgeTechnique: 'Традиционный',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Внутренний',
    description: 'Шов, выполняемый внутри одежды.',
    advantages: 'Аккуратный вид изнутри.',
    disadvantages: 'Может быть трудным в выполнении.',
    fabric: 'Все типы тканей',
    application: 'Шитье одежды.',
    edgeTechnique: 'Внутренний',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'Гамак',
    description: 'Шов, образующий форму гамакоподобного узора.',
    advantages: 'Оригинальный и интересный дизайн.',
    disadvantages: 'Может требовать навыков и терпения.',
    fabric: 'Тонкие и средние ткани',
    application: 'Декорирование одежды, аксессуары.',
    edgeTechnique: 'Гамак',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Гладь',
    description: 'Шов, который создаёт плоский и аккуратный вид.',
    advantages: 'Простота выполнения, универсальность.',
    disadvantages: 'Может быть менее декоративным.',
    fabric: 'Все типы тканей',
    application: 'Шитье и вышивка.',
    edgeTechnique: 'Плоский шов',
    embroidery: true,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 2,
  },
  {
    name: 'Гладь плоская косточкой',
    description: 'Шов с использованием косточки для создания плоского вида.',
    advantages: 'Эстетичный и прочный.',
    disadvantages: 'Необходима косточка, может быть трудным для новичков.',
    fabric: 'Тонкие и средние ткани',
    application: 'Декорирование, вышивка.',
    edgeTechnique: 'Плоский с косточкой',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Глазком',
    description: 'Шов, создающий эффект глазка на ткани.',
    advantages: 'Интересный декоративный элемент.',
    disadvantages: 'Может быть сложным в выполнении.',
    fabric: 'Тонкие ткани',
    application: 'Декорирование одежды.',
    edgeTechnique: 'Глазок',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Глазок алжирский',
    description: 'Шов, аналогичный глазку, но с особенностями алжирской вышивки.',
    advantages: 'Оригинальный вид, характерный для алжирской вышивки.',
    disadvantages: 'Сложность выполнения, требует навыков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Алжирский глазок',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Гобеленовый',
    description: 'Шов, используемый для создания гобеленовых узоров.',
    advantages: 'Создает богатые текстуры и узоры.',
    disadvantages: 'Требует специальных навыков.',
    fabric: 'Ткань для гобеленов',
    application: 'Декорирование, вышивка.',
    edgeTechnique: 'Гобелен',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: true,
    complexity: 5,
  },
  {
    name: 'Двойной строчкой',
    description: 'Шов с двумя параллельными строчками.',
    advantages: 'Прочный и надежный.',
    disadvantages: 'Может быть трудным для выполнения на толстой ткани.',
    fabric: 'Все типы тканей',
    application: 'Шитье и декоративные элементы.',
    edgeTechnique: 'Двойная строчка',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'Западка',
    description: 'Шов, который создает западки для декоративного оформления.',
    advantages: 'Эффектный и необычный вид.',
    disadvantages: 'Требует точности.',
    fabric: 'Тонкие ткани',
    application: 'Декорирование одежды.',
    edgeTechnique: 'Западка',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Зиг-заг',
    description: 'Шов, который образует зигзагообразный узор.',
    advantages: 'Эластичность, подходит для многих тканей.',
    disadvantages: 'Может быть сложным для ровных строчек.',
    fabric: 'Все типы тканей',
    application: 'Шитье, отделка краев.',
    edgeTechnique: 'Зиг-заг',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'Иголкой вперед',
    description: 'Шов, выполняемый иглой вперед.',
    advantages: 'Аккуратный и легкий в выполнении.',
    disadvantages: 'Может не подходить для всех тканей.',
    fabric: 'Тонкие ткани',
    application: 'Шитье, декоративные элементы.',
    edgeTechnique: 'Иголка вперед',
    embroidery: true,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 2,
  },
  {
    name: 'Иголкой назад',
    description: 'Шов, выполняемый иглой назад.',
    advantages: 'Создает интересный декоративный эффект.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Иголка назад',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Испанский',
    description: 'Шов, используемый в традиционном испанском рукоделии.',
    advantages: 'Традиционный вид, прочность.',
    disadvantages: 'Может потребовать навыков.',
    fabric: 'Все типы тканей',
    application: 'Декоративные элементы, вышивка.',
    edgeTechnique: 'Испанский',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Итальянский двусторонним крестом',
    description: 'Шов, выполняемый итальянским двусторонним крестом.',
    advantages: 'Эстетичный и прочный.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Двусторонний крест',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: true,
    complexity: 5,
  },
  {
    name: 'Колониальный',
    description: 'Шов, используемый в колониальном рукоделии.',
    advantages: 'Прочный и декоративный.',
    disadvantages: 'Требует навыков и терпения.',
    fabric: 'Все типы тканей',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Колониальный',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Коралловый',
    description: 'Шов, создающий узоры в виде кораллов.',
    advantages: 'Красивый декоративный эффект.',
    disadvantages: 'Может быть трудным в выполнении.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Коралловый узор',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Косичка',
    description: 'Шов, образующий узор косички.',
    advantages: 'Простой и декоративный.',
    disadvantages: 'Может быть менее прочным.',
    fabric: 'Все типы тканей',
    application: 'Шитье и вышивка.',
    edgeTechnique: 'Косичка',
    embroidery: true,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'Косточка открытая',
    description: 'Шов с открытой косточкой для декоративного оформления.',
    advantages: 'Интересный декоративный эффект.',
    disadvantages: 'Требуется косточка, может быть трудным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Декорирование одежды.',
    edgeTechnique: 'Открытая косточка',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Крест (ёлочка)',
    description: 'Шов в виде крестика, образующий узор ёлочки.',
    advantages: 'Простой и традиционный.',
    disadvantages: 'Может быть менее декоративным.',
    fabric: 'Все типы тканей',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Ёлочка',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 2,
  },
  {
    name: 'Крест (ёлочка) с прикрепом',
    description: 'Шов в виде крестика с прикрепом.',
    advantages: 'Устойчивый и декоративный.',
    disadvantages: 'Может требовать навыков.',
    fabric: 'Тонкие и средние ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Ёлочка с прикрепом',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: true,
    complexity: 4,
  },
  {
    name: 'Крест двойной',
    description: 'Шов в виде двойного крестика.',
    advantages: 'Эстетичный и заметный.',
    disadvantages: 'Может быть сложным в выполнении.',
    fabric: 'Тонкие и средние ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Двойной крест',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: true,
    complexity: 4,
  },
  {
    name: 'Крест черногорский',
    description: 'Шов в виде черногорского крестика.',
    advantages: 'Традиционный и прочный.',
    disadvantages: 'Может требовать опыта.',
    fabric: 'Тонкие ткани',
    application: 'Декорирование одежды, вышивка.',
    edgeTechnique: 'Черногорский крест',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: true,
    complexity: 4,
  },
  {
    name: 'Критский',
    description: 'Шов, используемый в критском рукоделии.',
    advantages: 'Уникальный и прочный.',
    disadvantages: 'Может быть сложным для новичков.',
    fabric: 'Все типы тканей',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Критский',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Лист',
    description: 'Шов, образующий узор в виде листа.',
    advantages: 'Простой и декоративный.',
    disadvantages: 'Может быть менее устойчивым.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Лист',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'Мозаичный',
    description: 'Шов, создающий мозаичный узор на ткани.',
    advantages: 'Яркий и интересный.',
    disadvantages: 'Может быть сложным в выполнении.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Мозаичный узор',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: true,
    complexity: 5,
  },
  {
    name: 'На утолщение',
    description: 'Шов, выполняемый для утолщения края ткани.',
    advantages: 'Устойчивый и прочный.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Толстые ткани',
    application: 'Обработка краев, укрепление.',
    edgeTechnique: 'Утолщение',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Назад иголку',
    description: 'Шов, выполняемый в обратном направлении иголкой.',
    advantages: 'Эффектный декоративный элемент.',
    disadvantages: 'Может быть сложным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Назад иголку',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Нить в прикреп',
    description: 'Шов, использующий нить в прикрепе.',
    advantages: 'Прочный и декоративный.',
    disadvantages: 'Требует навыков.',
    fabric: 'Тонкие и средние ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Нить в прикреп',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Папоротник',
    description: 'Шов, создающий узор в виде папоротника.',
    advantages: 'Интересный декоративный эффект.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Папоротник',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Парижский',
    description: 'Шов, используемый в парижском рукоделии.',
    advantages: 'Элегантный и прочный.',
    disadvantages: 'Может требовать специальных навыков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Парижский',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: true,
    complexity: 5,
  },
  {
    name: 'Переплет',
    description: 'Шов, который создаёт переплетение нитей.',
    advantages: 'Прочный и декоративный.',
    disadvantages: 'Может быть сложным в выполнении.',
    fabric: 'Все типы тканей',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Переплетение',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Петельный закрытый',
    description: 'Шов, образующий закрытые петли.',
    advantages: 'Прочный и аккуратный.',
    disadvantages: 'Может требовать навыков.',
    fabric: 'Тонкие и средние ткани',
    application: 'Обработка краев.',
    edgeTechnique: 'Закрытые петли',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'Петельный заполняющий',
    description: 'Шов, использующий заполнение петель.',
    advantages: 'Устойчивый и декоративный.',
    disadvantages: 'Может быть сложным в выполнении.',
    fabric: 'Все типы тканей',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Заполняющий',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Петельный обмёточный',
    description: 'Шов, применяемый для обмёточивания краев.',
    advantages: 'Прочный и аккуратный.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Все типы тканей',
    application: 'Обработка краев.',
    edgeTechnique: 'Обмёточный',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Петельный по кругу',
    description: 'Шов, образующий петли по кругу.',
    advantages: 'Интересный декоративный эффект.',
    disadvantages: 'Требует точности и навыков.',
    fabric: 'Тонкие и средние ткани',
    application: 'Декорирование, вышивка.',
    edgeTechnique: 'По кругу',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Петельный с обвязкой',
    description: 'Шов с обвязкой вокруг петель.',
    advantages: 'Прочный и декоративный.',
    disadvantages: 'Может требовать навыков.',
    fabric: 'Тонкие и средние ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'С обвязкой',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Петельный сплошной',
    description: 'Шов с сплошными петлями.',
    advantages: 'Простой и надежный.',
    disadvantages: 'Может быть менее декоративным.',
    fabric: 'Все типы тканей',
    application: 'Шитье и вышивка.',
    edgeTechnique: 'Сплошной',
    embroidery: true,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'Петля воздушная рококо',
    description: 'Шов, создающий воздушные петли в стиле рококо.',
    advantages: 'Эстетичный и интересный.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Декорирование, вышивка.',
    edgeTechnique: 'Воздушная рококо',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Петля вприкреп',
    description: 'Шов, применяемый для прикрепления петель.',
    advantages: 'Прочный и надежный.',
    disadvantages: 'Может требовать навыков.',
    fabric: 'Тонкие и средние ткани',
    application: 'Обработка краев, вышивка.',
    edgeTechnique: 'Вприкреп',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Полукрестом',
    description: 'Шов, образующий узор полукрестиком.',
    advantages: 'Простой и декоративный.',
    disadvantages: 'Может быть менее устойчивым.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Полукрест',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'Потайной',
    description: 'Шов, выполненный так, что его почти не видно.',
    advantages: 'Эстетичный и аккуратный.',
    disadvantages: 'Может быть сложным в выполнении.',
    fabric: 'Все типы тканей',
    application: 'Шитье, отделка.',
    edgeTechnique: 'Потайной',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Прямой',
    description: 'Шов, выполненный прямыми строчками.',
    advantages: 'Простой и надежный.',
    disadvantages: 'Может быть менее декоративным.',
    fabric: 'Все типы тканей',
    application: 'Шитье и отделка.',
    edgeTechnique: 'Прямой',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 2,
  },
  {
    name: 'Стебельчатый',
    description: 'Шов, образующий узор стебелька.',
    advantages: 'Простой и декоративный.',
    disadvantages: 'Может быть менее прочным.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Стебельчатый',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 3,
  },
  {
    name: 'Тамбурный ломаный',
    description: 'Шов, образующий ломаный узор с использованием тамбурного шва.',
    advantages: 'Интересный декоративный эффект.',
    disadvantages: 'Может быть сложным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Ломаный тамбурный',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Тамбурный открытый',
    description: 'Шов, выполняемый открытым тамбурным узором.',
    advantages: 'Простой и декоративный.',
    disadvantages: 'Может быть менее прочным.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Открытый тамбурный',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Тамбурный скрещенный',
    description: 'Шов, образующий скрещенные узоры с помощью тамбурного шва.',
    advantages: 'Интересный декоративный эффект.',
    disadvantages: 'Может быть сложным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Скрещенный тамбурный',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Тамбурный слева направо',
    description: 'Шов, выполняемый слева направо с использованием тамбурного узора.',
    advantages: 'Простой и эстетичный.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Слева направо тамбурный',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Тамбурный цепочкой',
    description: 'Шов, образующий цепочку с помощью тамбурного узора.',
    advantages: 'Эффектный и декоративный.',
    disadvantages: 'Может требовать опыта.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Цепочка тамбурная',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Трикотажный',
    description: 'Шов, применяемый для трикотажных тканей.',
    advantages: 'Эластичность и прочность.',
    disadvantages: 'Может быть сложным для новичков.',
    fabric: 'Трикотажные ткани',
    application: 'Шитье трикотажных изделий.',
    edgeTechnique: 'Трикотажный',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Тройной',
    description: 'Шов, выполненный с тремя параллельными строчками.',
    advantages: 'Прочный и надежный.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Все типы тканей',
    application: 'Шитье, декоративные элементы.',
    edgeTechnique: 'Тройной шов',
    embroidery: false,
    sewing: true,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Турецкий треугольный',
    description: 'Шов, образующий турецкий треугольный узор.',
    advantages: 'Оригинальный и декоративный.',
    disadvantages: 'Может быть сложным в выполнении.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Турецкий треугольник',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: true,
    complexity: 5,
  },
  {
    name: 'Фестон',
    description: 'Шов, образующий фестоноподобный узор.',
    advantages: 'Красивый декоративный эффект.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Фестон',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
  {
    name: 'Французский узелок',
    description: 'Шов, образующий французский узелок на ткани.',
    advantages: 'Интересный декоративный элемент.',
    disadvantages: 'Может быть трудным для новичков.',
    fabric: 'Все типы тканей',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Французский узелок',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Цепочка',
    description: 'Шов, создающий цепочку из стежков.',
    advantages: 'Эстетичный и прочный.',
    disadvantages: 'Может быть сложным в выполнении.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Цепочка',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 4,
  },
  {
    name: 'Чешуя',
    description: 'Шов, образующий узор в виде чешуи.',
    advantages: 'Оригинальный декоративный эффект.',
    disadvantages: 'Может быть сложным в выполнении.',
    fabric: 'Тонкие ткани',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Чешуя',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: true,
    complexity: 5,
  },
  {
    name: 'Шнур',
    description: 'Шов, создающий узор в виде шнура.',
    advantages: 'Эстетичный и прочный.',
    disadvantages: 'Может быть сложным для новичков.',
    fabric: 'Все типы тканей',
    application: 'Вышивка, декоративные элементы.',
    edgeTechnique: 'Шнур',
    embroidery: true,
    sewing: false,
    button: false,
    countedStitch: false,
    complexity: 5,
  },
]

const SeamList = () => {
  const [sortColumn, setSortColumn] = useState('name');
  const [sortOrder, setSortOrder] = useState('asc');

  // Функция для сортировки данных
  const sortData = (data, column, order) => {
    return [...data].sort((a, b) => {
      if (a[column] < b[column]) return order === 'asc' ? -1 : 1;
      if (a[column] > b[column]) return order === 'asc' ? 1 : -1;
      return 0;
    });
  };

  const sortedData = sortData(seamData, sortColumn, sortOrder);

  const handleSort = (column) => {
    const newOrder = sortColumn === column && sortOrder === 'asc' ? 'desc' : 'asc';
    setSortColumn(column);
    setSortOrder(newOrder);
  };

  return (
    <div>
      <h1>Типы швов</h1>
      <table>
        <thead>
          <tr>
            <th onClick={() => handleSort('name')}>Название</th>
            <th onClick={() => handleSort('description')}>Описание</th>
            <th onClick={() => handleSort('advantages')}>Преимущества</th>
            <th onClick={() => handleSort('disadvantages')}>Недостатки</th>
            <th onClick={() => handleSort('fabric')}>Для каких тканей</th>
            <th onClick={() => handleSort('application')}>Применение</th>
            <th onClick={() => handleSort('edgeTechnique')}>Техника отделки краев</th>
            <th onClick={() => handleSort('embroidery')}>Используется в вышивке</th>
            <th onClick={() => handleSort('sewing')}>Используется в шитье</th>
            <th onClick={() => handleSort('button')}>Используется для пуговиц</th>
            <th onClick={() => handleSort('countedStitch')}>Есть ли Счётным швом</th>
            <th onClick={() => handleSort('complexity')}>Сложность</th>
          </tr>
        </thead>
        <tbody>
          {sortedData.map((seam, index) => (
            <tr key={index}>
              <td>{seam.name}</td>
              <td>{seam.description}</td>
              <td>{seam.advantages}</td>
              <td>{seam.disadvantages}</td>
              <td>{seam.fabric}</td>
              <td>{seam.application}</td>
              <td>{seam.edgeTechnique}</td>
              <td>{seam.embroidery ? 'Да' : 'Нет'}</td>
              <td>{seam.sewing ? 'Да' : 'Нет'}</td>
              <td>{seam.button ? 'Да' : 'Нет'}</td>
              <td>{seam.countedStitch ? 'Да' : 'Нет'}</td>
              <td>{seam.complexity}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default SeamList;
