import React, { useState } from 'react';



const motorData = [
	{
	  name: 'Пружина',
	  description: 'Устройство, хранящее механическую энергию в виде упругих деформаций.',
	  advantages: ['Простота конструкции', 'Низкая стоимость'],
	  disadvantages: ['Ограниченный рабочий диапазон', 'Износ со временем'],
	  application: ['Механические устройства', 'Автомобильные системы'],
	  availability: 5,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 1,
	  lifespan: 10,
	  components: ['Металлическая пружина'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Поступательное',
	  movementType: 'Механическое',
	  nature: 'Механическое',
	  dc_ac: 'Не применимо',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Не применимо',
	  nominalVoltage: 'Не применимо',
	  nominalCurrent: 'Не применимо',
	  power: 'Не применимо',
	  maxRotationSpeed: 'Не применимо',
	  torque: 'Не применимо',
	  type: 'Пружина',
	  feedbackAccuracy: 'Не применимо',
	  efficiency: 'Не применимо',
	  size: 'Малый',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Не применимо',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: 'Широкий',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Не применимо',
	  vibrationImpactResistance: 'Высокая',
	  overheatingProtection: 'Не применимо',
	  responseTime: 'Не применимо',
	  positioningAccuracy: 'Не применимо',
	},
	{
	  name: 'Коллекторный двигатель',
	  description: 'Электродвигатель с коллектором и щетками, использующий постоянный ток.',
	  advantages: ['Простота управления', 'Низкая стоимость'],
	  disadvantages: ['Износ щеток', 'Шум при работе'],
	  application: ['Модели', 'Инструменты'],
	  availability: 4,
	  qualityAndReliability: 3,
	  manufacturingComplexity: 2,
	  lifespan: 5,
	  components: ['Коллектор', 'Щетки', 'Ротор', 'Статор'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Вращение',
	  movementType: 'Электрическое',
	  nature: 'Электрическое',
	  dc_ac: 'DC',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Не применимо',
	  nominalVoltage: '12V',
	  nominalCurrent: '1.5A',
	  power: '18W',
	  maxRotationSpeed: '10,000 RPM',
	  torque: '0.5Nm',
	  type: 'Коллекторный',
	  feedbackAccuracy: 'Средняя',
	  efficiency: 'Средняя',
	  size: 'Средний',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Среднее',
	  coolingMethod: 'Воздушное',
	  operatingTemperatureRange: '-10°C до 60°C',
	  externalImpactResistance: 'Низкая',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Отсутствует',
	  responseTime: 'Среднее',
	  positioningAccuracy: 'Не применимо',
	},
	{
	  name: 'Безколлекторный двигатель',
	  description: 'Электродвигатель без коллекторов и щеток, использующий постоянный ток и электронное управление.',
	  advantages: ['Долговечность', 'Меньше шума'],
	  disadvantages: ['Высокая стоимость', 'Сложность управления'],
	  application: ['Беспилотники', 'Серводвигатели'],
	  availability: 4,
	  qualityAndReliability: 5,
	  manufacturingComplexity: 3,
	  lifespan: 10,
	  components: ['Ротор', 'Статор', 'Электронный контроллер'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Вращение',
	  movementType: 'Электрическое',
	  nature: 'Электрическое',
	  dc_ac: 'DC',
	  synchronous_asynchronous: 'Синхронный',
	  controlType: 'Электронное',
	  nominalVoltage: '24V',
	  nominalCurrent: '2A',
	  power: '48W',
	  maxRotationSpeed: '20,000 RPM',
	  torque: '1Nm',
	  type: 'Безколлекторный',
	  feedbackAccuracy: 'Высокая',
	  efficiency: 'Высокая',
	  size: 'Средний',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Низкое',
	  coolingMethod: 'Воздушное',
	  operatingTemperatureRange: '-20°C до 70°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Низкий',
	  vibrationImpactResistance: 'Высокая',
	  overheatingProtection: 'Есть',
	  responseTime: 'Высокое',
	  positioningAccuracy: 'Высокая',
	},
	{
	  name: 'Клапан электромагнитный',
	  description: 'Устройство, использующее электромагнитное поле для управления потоком жидкости или газа.',
	  advantages: ['Высокая скорость работы', 'Компактность'],
	  disadvantages: ['Зависимость от питания', 'Механический износ'],
	  application: ['Системы автоматизации', 'Автомобильные системы'],
	  availability: 5,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 2,
	  lifespan: 8,
	  components: ['Электромагнит', 'Клапан', 'Корпус'],
	  driveMethod: 'Не применимо',
	  movementMechanism: 'Линейное движение',
	  movementType: 'Электромагнитное',
	  nature: 'Электромагнитное',
	  dc_ac: 'DC',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Электронное',
	  nominalVoltage: '12V',
	  nominalCurrent: '0.5A',
	  power: '6W',
	  maxRotationSpeed: 'Не применимо',
	  torque: 'Не применимо',
	  type: 'Электромагнитный',
	  feedbackAccuracy: 'Средняя',
	  efficiency: 'Средняя',
	  size: 'Малый',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Низкое',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: '-10°C до 50°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Низкий',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Отсутствует',
	  responseTime: 'Высокое',
	  positioningAccuracy: 'Средняя',
	},
	{
	  name: 'Соленоид защелка',
	  description: 'Электромагнитное устройство для фиксации и удержания в определенном положении.',
	  advantages: ['Простота конструкции', 'Надежность'],
	  disadvantages: ['Может быть шумным', 'Потребляет много энергии'],
	  application: ['Замки', 'Кнопки'],
	  availability: 4,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 2,
	  lifespan: 6,
	  components: ['Соленоид', 'Клеммы', 'Корпус'],
	  driveMethod: 'Не применимо',
	  movementMechanism: 'Линейное движение',
	  movementType: 'Электромагнитное',
	  nature: 'Электромагнитное',
	  dc_ac: 'DC',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Электронное',
	  nominalVoltage: '24V',
	  nominalCurrent: '1A',
	  power: '24W',
	  maxRotationSpeed: 'Не применимо',
	  torque: 'Не применимо',
	  type: 'Соленоид',
	  feedbackAccuracy: 'Средняя',
	  efficiency: 'Средняя',
	  size: 'Малый',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Среднее',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: '-10°C до 60°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Отсутствует',
	  responseTime: 'Высокое',
	  positioningAccuracy: 'Средняя',
	},
	{
	  name: 'Реле',
	  description: 'Электромеханическое устройство для переключения электрических цепей.',
	  advantages: ['Высокая надежность', 'Может переключать большие токи'],
	  disadvantages: ['Медленный отклик', 'Износ контактов'],
	  application: ['Электрические системы', 'Автоматизация'],
	  availability: 5,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 2,
	  lifespan: 10,
	  components: ['Контакты', 'Катушка', 'Корпус'],
	  driveMethod: 'Не применимо',
	  movementMechanism: 'Линейное движение',
	  movementType: 'Электромеханическое',
	  nature: 'Электромеханическое',
	  dc_ac: 'AC',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Не применимо',
	  nominalVoltage: '230V',
	  nominalCurrent: '10A',
	  power: '2W',
	  maxRotationSpeed: 'Не применимо',
	  torque: 'Не применимо',
	  type: 'Реле',
	  feedbackAccuracy: 'Не применимо',
	  efficiency: 'Средняя',
	  size: 'Малый',
	  shape: 'Прямоугольная',
	  energyConsumption: 'Низкое',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: '-20°C до 70°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Отсутствует',
	  responseTime: 'Среднее',
	  positioningAccuracy: 'Не применимо',
	},
	{
	  name: 'Актуатор',
	  description: 'Устройство, преобразующее энергию в механическое движение.',
	  advantages: ['Может выполнять различные типы движений', 'Высокая точность'],
	  disadvantages: ['Высокая стоимость', 'Сложность управления'],
	  application: ['Автоматика', 'Системы управления'],
	  availability: 4,
	  qualityAndReliability: 5,
	  manufacturingComplexity: 3,
	  lifespan: 8,
	  components: ['Мотор', 'Передача', 'Корпус'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Линейное/Вращательное движение',
	  movementType: 'Электрическое/Гидравлическое/Пневматическое',
	  nature: 'Электрическое/Гидравлическое/Пневматическое',
	  dc_ac: 'DC/AC',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Электронное',
	  nominalVoltage: '24V',
	  nominalCurrent: '2A',
	  power: '48W',
	  maxRotationSpeed: 'Не применимо',
	  torque: '1.5Nm',
	  type: 'Актуатор',
	  feedbackAccuracy: 'Высокая',
	  efficiency: 'Высокая',
	  size: 'Средний',
	  shape: 'Цилиндрическая/Прямоугольная',
	  energyConsumption: 'Среднее',
	  coolingMethod: 'Воздушное',
	  operatingTemperatureRange: '-10°C до 60°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Низкий',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Есть',
	  responseTime: 'Высокое',
	  positioningAccuracy: 'Высокая',
	},
	{
	  name: 'Двигатель с редуктором',
	  description: 'Электродвигатель с встроенным редуктором для изменения скорости и крутящего момента.',
	  advantages: ['Высокий крутящий момент', 'Регулируемая скорость'],
	  disadvantages: ['Большие размеры', 'Сложность конструкции'],
	  application: ['Приводы', 'Роботы'],
	  availability: 4,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 3,
	  lifespan: 7,
	  components: ['Мотор', 'Редуктор', 'Корпус'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Вращение',
	  movementType: 'Электрическое',
	  nature: 'Электрическое',
	  dc_ac: 'DC/AC',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Электронное',
	  nominalVoltage: '12V',
	  nominalCurrent: '3A',
	  power: '36W',
	  maxRotationSpeed: '5,000 RPM',
	  torque: '3Nm',
	  type: 'Двигатель с редуктором',
	  feedbackAccuracy: 'Средняя',
	  efficiency: 'Средняя',
	  size: 'Большой',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Среднее',
	  coolingMethod: 'Воздушное',
	  operatingTemperatureRange: '-10°C до 50°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Есть',
	  responseTime: 'Среднее',
	  positioningAccuracy: 'Средняя',
	},
	{
	  name: 'Двигатели с прямым приводом',
	  description: 'Электродвигатели, непосредственно передающие движение на рабочий орган без промежуточных механизмов.',
	  advantages: ['Высокая точность', 'Минимум механических потерь'],
	  disadvantages: ['Высокая стоимость', 'Сложность управления'],
	  application: ['Станки', 'Роботы'],
	  availability: 3,
	  qualityAndReliability: 5,
	  manufacturingComplexity: 4,
	  lifespan: 10,
	  components: ['Мотор', 'Передача', 'Корпус'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Вращение/Линейное движение',
	  movementType: 'Электрическое',
	  nature: 'Электрическое',
	  dc_ac: 'DC/AC',
	  synchronous_asynchronous: 'Синхронный',
	  controlType: 'Электронное',
	  nominalVoltage: '48V',
	  nominalCurrent: '5A',
	  power: '240W',
	  maxRotationSpeed: '6,000 RPM',
	  torque: '5Nm',
	  type: 'Прямой привод',
	  feedbackAccuracy: 'Высокая',
	  efficiency: 'Высокая',
	  size: 'Большой',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Высокое',
	  coolingMethod: 'Воздушное',
	  operatingTemperatureRange: '-20°C до 60°C',
	  externalImpactResistance: 'Высокая',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Высокая',
	  overheatingProtection: 'Есть',
	  responseTime: 'Высокое',
	  positioningAccuracy: 'Высокая',
	},
	{
	  name: 'Двигатель AC',
	  description: 'Электродвигатель, работающий на переменном токе.',
	  advantages: ['Долговечность', 'Меньше обслуживания'],
	  disadvantages: ['Сложность управления скоростью', 'Высокие начальные затраты'],
	  application: ['Промышленные системы', 'Потребительская электроника'],
	  availability: 5,
	  qualityAndReliability: 5,
	  manufacturingComplexity: 3,
	  lifespan: 15,
	  components: ['Статор', 'Ротор', 'Корпус'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Вращение',
	  movementType: 'Электрическое',
	  nature: 'Электрическое',
	  dc_ac: 'AC',
	  synchronous_asynchronous: 'Асинхронный',
	  controlType: 'Не применимо',
	  nominalVoltage: '230V',
	  nominalCurrent: '10A',
	  power: '2.3kW',
	  maxRotationSpeed: '3,000 RPM',
	  torque: '5Nm',
	  type: 'AC',
	  feedbackAccuracy: 'Средняя',
	  efficiency: 'Средняя',
	  size: 'Большой',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Среднее',
	  coolingMethod: 'Воздушное',
	  operatingTemperatureRange: '-10°C до 70°C',
	  externalImpactResistance: 'Высокая',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Высокая',
	  overheatingProtection: 'Есть',
	  responseTime: 'Среднее',
	  positioningAccuracy: 'Средняя',
	},
	{
	  name: 'Электродвигатель',
	  description: 'Устройство, преобразующее электрическую энергию в механическое движение.',
	  advantages: ['Широкий спектр применения', 'Долговечность'],
	  disadvantages: ['Потребляет электричество', 'Требует обслуживания'],
	  application: ['Промышленные машины', 'Бытовая техника'],
	  availability: 5,
	  qualityAndReliability: 5,
	  manufacturingComplexity: 3,
	  lifespan: 10,
	  components: ['Статор', 'Ротор', 'Щетки'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Вращение',
	  movementType: 'Электрическое',
	  nature: 'Электрическое',
	  dc_ac: 'DC/AC',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Не применимо',
	  nominalVoltage: '220V',
	  nominalCurrent: '5A',
	  power: '1kW',
	  maxRotationSpeed: '3,000 RPM',
	  torque: '2Nm',
	  type: 'Электродвигатель',
	  feedbackAccuracy: 'Средняя',
	  efficiency: 'Средняя',
	  size: 'Средний',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Среднее',
	  coolingMethod: 'Воздушное',
	  operatingTemperatureRange: '-10°C до 50°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Есть',
	  responseTime: 'Среднее',
	  positioningAccuracy: 'Средняя',
	},
	{
	  name: 'Шаговый двигатель',
	  description: 'Двигатель, который делает движения шаг за шагом для точного контроля.',
	  advantages: ['Высокая точность', 'Легкость в управлении'],
	  disadvantages: ['Может быть шумным', 'Меньшая эффективность'],
	  application: ['Станки с ЧПУ', 'Принтеры'],
	  availability: 4,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 3,
	  lifespan: 8,
	  components: ['Статор', 'Ротор', 'Корпус'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Вращение',
	  movementType: 'Электрическое',
	  nature: 'Электрическое',
	  dc_ac: 'DC',
	  synchronous_asynchronous: 'Синхронный',
	  controlType: 'Электронное',
	  nominalVoltage: '5V',
	  nominalCurrent: '1A',
	  power: '5W',
	  maxRotationSpeed: '1,000 RPM',
	  torque: '0.2Nm',
	  type: 'Шаговый',
	  feedbackAccuracy: 'Высокая',
	  efficiency: 'Средняя',
	  size: 'Малый',
	  shape: 'Кубическая',
	  energyConsumption: 'Низкое',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: '-10°C до 50°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Отсутствует',
	  responseTime: 'Высокое',
	  positioningAccuracy: 'Высокая',
	},
	{
	  name: 'Серводвигатель',
	  description: 'Двигатель, который используется для высокоточного управления положением.',
	  advantages: ['Высокая точность', 'Широкий диапазон управления'],
	  disadvantages: ['Высокая стоимость', 'Сложность настройки'],
	  application: ['Роботы', 'Автоматизированные системы'],
	  availability: 3,
	  qualityAndReliability: 5,
	  manufacturingComplexity: 4,
	  lifespan: 10,
	  components: ['Мотор', 'Датчик', 'Контроллер'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Вращение/Линейное движение',
	  movementType: 'Электрическое',
	  nature: 'Электрическое',
	  dc_ac: 'DC',
	  synchronous_asynchronous: 'Синхронный',
	  controlType: 'Электронное',
	  nominalVoltage: '24V',
	  nominalCurrent: '2A',
	  power: '48W',
	  maxRotationSpeed: '3,000 RPM',
	  torque: '1Nm',
	  type: 'Серводвигатель',
	  feedbackAccuracy: 'Высокая',
	  efficiency: 'Высокая',
	  size: 'Средний',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Среднее',
	  coolingMethod: 'Воздушное',
	  operatingTemperatureRange: '-10°C до 60°C',
	  externalImpactResistance: 'Высокая',
	  noiseLevel: 'Низкий',
	  vibrationImpactResistance: 'Высокая',
	  overheatingProtection: 'Есть',
	  responseTime: 'Высокое',
	  positioningAccuracy: 'Высокая',
	},
	{
	  name: 'Вибромотор',
	  description: 'Мотор, создающий вибрации для различных приложений.',
	  advantages: ['Компактность', 'Простота управления'],
	  disadvantages: ['Ограниченная мощность', 'Может быть шумным'],
	  application: ['Мобильные устройства', 'Массажные устройства'],
	  availability: 4,
	  qualityAndReliability: 3,
	  manufacturingComplexity: 2,
	  lifespan: 5,
	  components: ['Вибратор', 'Мотор', 'Корпус'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Вибрационное движение',
	  movementType: 'Электрическое',
	  nature: 'Электрическое',
	  dc_ac: 'DC',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Не применимо',
	  nominalVoltage: '5V',
	  nominalCurrent: '0.5A',
	  power: '2.5W',
	  maxRotationSpeed: 'Не применимо',
	  torque: 'Не применимо',
	  type: 'Вибромотор',
	  feedbackAccuracy: 'Не применимо',
	  efficiency: 'Средняя',
	  size: 'Малый',
	  shape: 'Кубическая',
	  energyConsumption: 'Низкое',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: '-10°C до 50°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Отсутствует',
	  responseTime: 'Среднее',
	  positioningAccuracy: 'Не применимо',
	},
	{
	  name: 'Пьезодвигатель',
	  description: 'Двигатель, использующий пьезоэлектрический эффект для создания движения.',
	  advantages: ['Очень точное управление', 'Малые размеры'],
	  disadvantages: ['Высокая стоимость', 'Ограниченная мощность'],
	  application: ['Оптические системы', 'Медицинские устройства'],
	  availability: 3,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 4,
	  lifespan: 6,
	  components: ['Пьезоэлемент', 'Корпус', 'Электронный контроллер'],
	  driveMethod: 'Прямой привод',
	  movementMechanism: 'Пьезоэлектрическое движение',
	  movementType: 'Поступательное/Колебательное',
	  nature: 'Пьезоэлектрическое',
	  dc_ac: 'Не применимо',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Электронное',
	  nominalVoltage: '100V',
	  nominalCurrent: '0.1A',
	  power: '10W',
	  maxRotationSpeed: 'Не применимо',
	  torque: 'Не применимо',
	  type: 'Пьезодвигатель',
	  feedbackAccuracy: 'Высокая',
	  efficiency: 'Высокая',
	  size: 'Малый',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Низкое',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: '-20°C до 60°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Низкий',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Отсутствует',
	  responseTime: 'Высокое',
	  positioningAccuracy: 'Высокая',
	},
	{
	  name: 'Гидро мотор',
	  description: 'Мотор, использующий гидравлическое давление для создания механического движения.',
	  advantages: ['Высокий крутящий момент', 'Мощность'],
	  disadvantages: ['Высокие затраты на обслуживание', 'Необходимость в жидкости'],
	  application: ['Промышленные системы', 'Техническое оборудование'],
	  availability: 3,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 4,
	  lifespan: 8,
	  components: ['Поршень', 'Цилиндр', 'Насос'],
	  driveMethod: 'Гидравлический привод',
	  movementMechanism: 'Вращение/Линейное движение',
	  movementType: 'Гидравлическое',
	  nature: 'Гидравлическое',
	  dc_ac: 'Не применимо',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Не применимо',
	  nominalVoltage: 'Не применимо',
	  nominalCurrent: 'Не применимо',
	  power: '3kW',
	  maxRotationSpeed: '2,000 RPM',
	  torque: '10Nm',
	  type: 'Гидро мотор',
	  feedbackAccuracy: 'Средняя',
	  efficiency: 'Средняя',
	  size: 'Большой',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Высокое',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: '-20°C до 80°C',
	  externalImpactResistance: 'Высокая',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Высокая',
	  overheatingProtection: 'Есть',
	  responseTime: 'Среднее',
	  positioningAccuracy: 'Средняя',
	},
	{
	  name: 'Гидро поршень',
	  description: 'Поршень, использующий гидравлическое давление для создания линейного движения.',
	  advantages: ['Высокий крутящий момент', 'Высокая надежность'],
	  disadvantages: ['Необходимость в гидравлической жидкости', 'Сложность в обслуживании'],
	  application: ['Промышленные машины', 'Автоматизация'],
	  availability: 3,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 4,
	  lifespan: 10,
	  components: ['Поршень', 'Цилиндр', 'Гидравлический насос'],
	  driveMethod: 'Гидравлический привод',
	  movementMechanism: 'Линейное движение',
	  movementType: 'Гидравлическое',
	  nature: 'Гидравлическое',
	  dc_ac: 'Не применимо',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Не применимо',
	  nominalVoltage: 'Не применимо',
	  nominalCurrent: 'Не применимо',
	  power: '2kW',
	  maxRotationSpeed: 'Не применимо',
	  torque: 'Не применимо',
	  type: 'Гидро поршень',
	  feedbackAccuracy: 'Средняя',
	  efficiency: 'Средняя',
	  size: 'Средний',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Высокое',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: '-20°C до 80°C',
	  externalImpactResistance: 'Высокая',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Высокая',
	  overheatingProtection: 'Есть',
	  responseTime: 'Среднее',
	  positioningAccuracy: 'Средняя',
	},
	{
	  name: 'Пневматический цилиндр',
	  description: 'Цилиндр, использующий сжатый воздух для создания линейного движения.',
	  advantages: ['Высокая скорость', 'Простота управления'],
	  disadvantages: ['Ограниченная точность', 'Зависимость от источника сжатого воздуха'],
	  application: ['Автоматизация', 'Промышленные машины'],
	  availability: 4,
	  qualityAndReliability: 4,
	  manufacturingComplexity: 2,
	  lifespan: 6,
	  components: ['Цилиндр', 'Поршень', 'Входное соединение'],
	  driveMethod: 'Пневматический привод',
	  movementMechanism: 'Линейное движение',
	  movementType: 'Пневматическое',
	  nature: 'Пневматическое',
	  dc_ac: 'Не применимо',
	  synchronous_asynchronous: 'Не применимо',
	  controlType: 'Не применимо',
	  nominalVoltage: 'Не применимо',
	  nominalCurrent: 'Не применимо',
	  power: '1.5kW',
	  maxRotationSpeed: 'Не применимо',
	  torque: 'Не применимо',
	  type: 'Пневматический цилиндр',
	  feedbackAccuracy: 'Средняя',
	  efficiency: 'Средняя',
	  size: 'Средний',
	  shape: 'Цилиндрическая',
	  energyConsumption: 'Высокое',
	  coolingMethod: 'Не применимо',
	  operatingTemperatureRange: '-20°C до 70°C',
	  externalImpactResistance: 'Средняя',
	  noiseLevel: 'Средний',
	  vibrationImpactResistance: 'Средняя',
	  overheatingProtection: 'Отсутствует',
	  responseTime: 'Высокое',
	  positioningAccuracy: 'Средняя',
	}
  ]



const MotorList = () => {
  const [sortConfig, setSortConfig] = useState({ key: '', direction: 'asc' });

  const sortedData = React.useMemo(() => {
    let sortableItems = [...motorData];
    if (sortConfig.key) {
      sortableItems.sort((a, b) => {
        if (a[sortConfig.key] < b[sortConfig.key]) {
          return sortConfig.direction === 'asc' ? -1 : 1;
        }
        if (a[sortConfig.key] > b[sortConfig.key]) {
          return sortConfig.direction === 'asc' ? 1 : -1;
        }
        return 0;
      });
    }
    return sortableItems;
  }, [sortConfig]);

  const requestSort = (key) => {
    let direction = 'asc';
    if (sortConfig.key === key && sortConfig.direction === 'asc') {
      direction = 'desc';
    }
    setSortConfig({ key, direction });
  };

  return (
    <div>
      <h1>Движители</h1>
      <table>
        <thead>
          <tr>
            <th onClick={() => requestSort('name')}>Название</th>
            <th onClick={() => requestSort('description')}>Описание</th>
            <th onClick={() => requestSort('advantages')}>Преимущества</th>
            <th onClick={() => requestSort('disadvantages')}>Недостатки</th>
            <th onClick={() => requestSort('application')}>Применение</th>
            <th onClick={() => requestSort('availability')}>Доступность</th>
            <th onClick={() => requestSort('qualityAndReliability')}>Качество и надежность</th>
            <th onClick={() => requestSort('manufacturingComplexity')}>Сложность изготовления</th>
            <th onClick={() => requestSort('lifespan')}>Срок службы (лет)</th>
            <th onClick={() => requestSort('components')}>Компоненты изготовления</th>
            <th onClick={() => requestSort('driveMethod')}>Способ передачи движения</th>
            <th onClick={() => requestSort('movementMechanism')}>Механизм движения</th>
            <th onClick={() => requestSort('movementType')}>Способ движения</th>
            <th onClick={() => requestSort('nature')}>Природа</th>
            <th onClick={() => requestSort('dc_ac')}>DC/AC</th>
            <th onClick={() => requestSort('synchronous_asynchronous')}>Синхрон/Асинхрон</th>
            <th onClick={() => requestSort('controlType')}>Тип управления</th>
            <th onClick={() => requestSort('nominalVoltage')}>Номинальное напряжение</th>
            <th onClick={() => requestSort('nominalCurrent')}>Номинальный ток</th>
            <th onClick={() => requestSort('power')}>Мощность</th>
            <th onClick={() => requestSort('maxRotationSpeed')}>Максимальная скорость вращения</th>
            <th onClick={() => requestSort('torque')}>Крутящий момент</th>
            <th onClick={() => requestSort('type')}>Тип</th>
            <th onClick={() => requestSort('feedbackAccuracy')}>Точность обратной связи</th>
            <th onClick={() => requestSort('efficiency')}>Эффективность</th>
            <th onClick={() => requestSort('size')}>Размер</th>
            <th onClick={() => requestSort('shape')}>Форма</th>
            <th onClick={() => requestSort('energyConsumption')}>Энергопотребление</th>
            <th onClick={() => requestSort('coolingMethod')}>Способ охлаждения</th>
            <th onClick={() => requestSort('operatingTemperatureRange')}>Диапазон рабочей температуры</th>
            <th onClick={() => requestSort('externalImpactResistance')}>Устойчивость к внешним воздействиям</th>
            <th onClick={() => requestSort('noiseLevel')}>Уровень шума</th>
            <th onClick={() => requestSort('vibrationImpactResistance')}>Сопротивляемость к вибрациям и ударам</th>
            <th onClick={() => requestSort('overheatingProtection')}>Защита от перегрева</th>
            <th onClick={() => requestSort('responseTime')}>Время отклика</th>
            <th onClick={() => requestSort('positioningAccuracy')}>Уровень точности позиционирования</th>
          </tr>
        </thead>
        <tbody>
          {sortedData.map((motor, index) => (
            <tr key={index}>
              <td>{motor.name}</td>
              <td>{motor.description}</td>
              <td>{motor.advantages.join(', ')}</td>
              <td>{motor.disadvantages.join(', ')}</td>
              <td>{motor.application.join(', ')}</td>
              <td>{motor.availability}</td>
              <td>{motor.qualityAndReliability}</td>
              <td>{motor.manufacturingComplexity}</td>
              <td>{motor.lifespan}</td>
              <td>{motor.components.join(', ')}</td>
              <td>{motor.driveMethod}</td>
              <td>{motor.movementMechanism}</td>
              <td>{motor.movementType}</td>
              <td>{motor.nature}</td>
              <td>{motor.dc_ac}</td>
              <td>{motor.synchronous_asynchronous}</td>
              <td>{motor.controlType}</td>
              <td>{motor.nominalVoltage}</td>
              <td>{motor.nominalCurrent}</td>
              <td>{motor.power}</td>
              <td>{motor.maxRotationSpeed}</td>
              <td>{motor.torque}</td>
              <td>{motor.type}</td>
              <td>{motor.feedbackAccuracy}</td>
              <td>{motor.efficiency}</td>
              <td>{motor.size}</td>
              <td>{motor.shape}</td>
              <td>{motor.energyConsumption}</td>
              <td>{motor.coolingMethod}</td>
              <td>{motor.operatingTemperatureRange}</td>
              <td>{motor.externalImpactResistance}</td>
              <td>{motor.noiseLevel}</td>
              <td>{motor.vibrationImpactResistance}</td>
              <td>{motor.overheatingProtection}</td>
              <td>{motor.responseTime}</td>
              <td>{motor.positioningAccuracy}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default MotorList;
