
export const FUNCTION_GROUPS = {
  BASIC: "Основные",
  REVERSE: "Обратные",
  HYPERBOLIC: "Гипербол",
  GA: "Га",
  VER: "Вер",
  EX: "Экс",
};

export const TRIGONOMETRIC_FUNCTIONS = {
  sin: {
    group: FUNCTION_GROUPS.BASIC,
    nameModernFull: "sinus",
    nameModernSort: "sin",
    nameRealFull: "сатус",
    nameRealSort: "стс",
    func: (x) => Math.sin(x),
    color: "#00008B",
    description:
      "Синус угла. Определяет отношение противолежащего катета к гипотенузе.",
  },
  cos: {
    group: FUNCTION_GROUPS.BASIC,
    nameModernFull: "cosinus",
    nameModernSort: "cos",
    nameRealFull: "сакус",
    nameRealSort: "скс",
    func: (x) => Math.cos(x),
    color: "#006400",
    description:
      "Косинус угла. Определяет отношение прилежащего катета к гипотенузе.",
  },
  tan: {
    group: FUNCTION_GROUPS.BASIC,
    nameModernFull: "tangens",
    nameModernSort: "tan",
    nameRealFull: "тангенус",
    nameRealSort: "тнг",
    func: (x) => Math.tan(x),
    color: "#8B008B",
    description: "Тангенс угла. Определяет отношение синуса угла к косинусу.",
  },
  cot: {
    group: FUNCTION_GROUPS.BASIC,
    nameModernFull: "cotangens",
    nameModernSort: "cot",
    nameRealFull: "котангенус",
    nameRealSort: "ктнг",
    func: (x) => 1 / Math.tan(x),
    color: "#FF8C00",
    description: "Котангенс угла. Определяет отношение косинуса угла к синусу.",
  },
  sec: {
    group: FUNCTION_GROUPS.BASIC,
    nameModernFull: "secans",
    nameModernSort: "sec",
    nameRealFull: "косакусъ",
    nameRealSort: "кскс",
    func: (x) => 1 / Math.cos(x),
    color: "#483D8B",
    description: "Секанс угла. Определяет обратную величину косинуса угла.",
  },
  csc: {
    group: FUNCTION_GROUPS.BASIC,
    nameModernFull: "cosecans",
    nameModernSort: "csc",
    nameRealFull: "косатусъ",
    nameRealSort: "кстс",
    func: (x) => 1 / Math.sin(x),
    color: "#1E90FF",
    description: "Косеканс угла. Определяет обратную величину синуса угла.",
  },

  arcsin: {
    group: FUNCTION_GROUPS.REVERSE,
    nameModernFull: "arcsinus",
    nameModernSort: "arcsin",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.asin(x),
    color: "#696969",
    description:
      "Арксинус угла. Определяет угол по известному значению синуса.",
  },
  arccos: {
    group: FUNCTION_GROUPS.REVERSE,
    nameModernFull: "arccosinus",
    nameModernSort: "arccos",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.acos(x),
    color: "#9400D3",
    description:
      "Арккосинус угла. Определяет угол по известному значению косинуса.",
  },
  arctan: {
    group: FUNCTION_GROUPS.REVERSE,
    nameModernFull: "arctangens",
    nameModernSort: "arctan",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.atan(x),
    color: "#CD5C5C",
    description:
      "Арктангенс угла. Определяет угол по известному значению тангенса.",
  },
  arccot: {
    group: FUNCTION_GROUPS.REVERSE,
    nameModernFull: "arccotangens",
    nameModernSort: "arccot",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.atan(1 / x),
    color: "#FFD700",
    description:
      "Арккотангенс угла. Определяет угол по известному значению котангенса.",
  },
  arcsec: {
    group: FUNCTION_GROUPS.REVERSE,
    nameModernFull: "arcsecans",
    nameModernSort: "arcsec",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.acos(1 / x),
    color: "#7CFC00",
    description:
      "Арксеканс угла. Определяет угол по известному значению секанса.",
  },
  arccsc: {
    group: FUNCTION_GROUPS.REVERSE,
    nameModernFull: "arccosecans",
    nameModernSort: "arccsc",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.asin(1 / x),
    color: "#FF4500",
    description:
      "Арккосеканс угла. Определяет угол по известному значению косеканса.",
  },

  sinh: {
    group: FUNCTION_GROUPS.HYPERBOLIC,
    nameModernFull: "hyperbolic sinus",
    nameModernSort: "sinh",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.sinh(x),
    color: "#FFA500",
    description:
      "Гиперболический синус угла. Определяет гиперболический синус угла.",
  },
  cosh: {
    group: FUNCTION_GROUPS.HYPERBOLIC,
    nameModernFull: "hyperbolic cosinus",
    nameModernSort: "cosh",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.cosh(x),
    color: "#DB7093",
    description:
      "Гиперболический косинус угла. Определяет гиперболический косинус угла.",
  },
  tanh: {
    group: FUNCTION_GROUPS.HYPERBOLIC,
    nameModernFull: "hyperbolic tangens",
    nameModernSort: "tanh",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.tanh(x),
    color: "#7B68EE",
    description:
      "Гиперболический тангенс угла. Определяет гиперболический тангенс угла.",
  },
  coth: {
    group: FUNCTION_GROUPS.HYPERBOLIC,
    nameModernFull: "hyperbolic cotangens",
    nameModernSort: "coth",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => 1 / Math.tanh(x),
    color: "#3CB371",
    description:
      "Гиперболический котангенс угла. Определяет гиперболический котангенс угла.",
  },
  sech: {
    group: FUNCTION_GROUPS.HYPERBOLIC,
    nameModernFull: "hyperbolic secans",
    nameModernSort: "sech",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => 1 / Math.cosh(x),
    color: "#0000CD",
    description:
      "Гиперболический секанс угла. Определяет гиперболический секанс угла.",
  },
  csch: {
    group: FUNCTION_GROUPS.HYPERBOLIC,
    nameModernFull: "hyperbolic cosecans",
    nameModernSort: "csch",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => 1 / Math.sinh(x),
    color: "#4B0082",
    description:
      "Гиперболический косеканс угла. Определяет гиперболический косеканс угла.",
  },

  versin: {
    group: FUNCTION_GROUPS.VER,
    nameModernFull: "versinus",
    nameModernSort: "versin",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => 1 - Math.cos(x),
    color: "#BA55D3",
    description: "Версинус угла. Определяет значение 1 - косинус угла.",
  },
  vercos: {
    group: FUNCTION_GROUPS.VER,
    nameModernFull: "vercosinus",
    nameModernSort: "vercos",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => 1 + Math.cos(x),
    color: "#800000",
    description: "Веркосинус угла. Определяет значение 1 + косинус угла.",
  },
  covers: {
    group: FUNCTION_GROUPS.VER,
    nameModernFull: "coversinus",
    nameModernSort: "covers",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => 1 - Math.sin(x),
    color: "#008080",
    description: "Коверсинус угла. Определяет значение 1 - синус угла.",
  },
  covercos: {
    group: FUNCTION_GROUPS.VER,
    nameModernFull: "covercosinus",
    nameModernSort: "covercos",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => 1 + Math.sin(x),
    color: "#6A5ACD",
    description: "Коверкосинус угла. Определяет значение 1 + синус угла.",
  },

  havers: {
    group: FUNCTION_GROUPS.GA,
    nameModernFull: "haversinus",
    nameModernSort: "havers",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => (1 - Math.cos(x)) / 2,
    color: "#8B4513",
    description: "Гаверсинус угла. Определяет половину версинуса угла.",
  },
  havercos: {
    group: FUNCTION_GROUPS.GA,
    nameModernFull: "havercosinus",
    nameModernSort: "havercos",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => (1 + Math.cos(x)) / 2,
    color: "#2E8B57",
    description: "Гаверкосинус угла. Определяет половину веркосинуса угла.",
  },
  hacovers: {
    group: FUNCTION_GROUPS.GA,
    nameModernFull: "hacoversinus",
    nameModernSort: "hacovers",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => (1 - Math.sin(x)) / 2,
    color: "#663399",
    description: "Гаковерсинус угла. Определяет половину коверсинуса угла.",
  },
  hacovercos: {
    group: FUNCTION_GROUPS.GA,
    nameModernFull: "hacovercosinus",
    nameModernSort: "hacovercos",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => (1 + Math.sin(x)) / 2,
    color: "#0000FF",
    description: "Гаковеркосинус угла. Определяет половину коверкосинуса угла.",
  },
  gaversin: {
    group: FUNCTION_GROUPS.GA,
    nameModernFull: "gaversin",
    nameModernSort: "gaversin",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.log(Math.sin(x / 2)),
    color: "#6495ED",
    description: "Гаверсинус угла. Определяет логарифм синуса половины угла.",
  },
  gaverkcos: {
    group: FUNCTION_GROUPS.GA,
    nameModernFull: "gaverscos",
    nameModernSort: "gaverscos",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.log(Math.sqrt((1 + Math.cos(x)) / 2)),
    color: "#4169E1",
    description:
      "Гаверкосинус угла. Определяет логарифм квадратного корня из половины суммы единицы и косинуса угла.",
  },
  gaversinC: {
    group: FUNCTION_GROUPS.GA,
    nameModernFull: "gaversinC",
    nameModernSort: "gaversinC",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.log(1 - Math.sin(x / 2)),
    color: "#8A2BE2",
    description:
      "Гаковерсинус угла. Определяет логарифм разности единицы и синуса половины угла.",
  },
  gaverkcosC: {
    group: FUNCTION_GROUPS.GA,
    nameModernFull: "gaverscosC ???",
    nameModernSort: "gaverscosC ???",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => Math.log(Math.sqrt((1 - Math.cos(x)) / 2)),
    color: "#FF7F50",
    description:
      "Гаковеркосинус угла. Определяет логарифм квадратного корня из половины разности единицы и косинуса угла.",
  },
  exsec: {
    group: FUNCTION_GROUPS.EX,
    nameModernFull: "exsecans",
    nameModernSort: "exsec",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => 1 / Math.cos(x) - 1,
    color: "#D2691E",
    description: "Exsecant of the angle. Defines the difference between secant and one.",
  },
  excsc: {
    group: FUNCTION_GROUPS.EX,
    nameModernFull: "excosecant",
    nameModernSort: "excsc",
    nameRealFull: "",
    nameRealSort: "",
    func: (x) => 1 / Math.sin(x) - 1,
    color: "#FA8072",
    description: "Excosecant of the angle. Defines the difference between cosecant and one.",
  },
};
